# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:  
    - uses: actions/checkout@v3

    - name: Clean Derived Data
      run: rm -rf ~/Library/Developer/Xcode/DerivedData

    # Build and test the Core package
    - name: Set up build directory for Core
      run: echo "PACKAGE_DIR=Core" >> $GITHUB_ENV

    - name: Run tests for Core
      run: swift test -v
      working-directory: ${{ env.PACKAGE_DIR }}

    # Build and test for the web-browser project on MacOS
    - name: Test for MacOS client
      run: xcodebuild test -scheme "web-browser" -destination "platform=macOS" -verbose CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      working-directory: web-browser
